name: money_records_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.3.59
  table_calendar: ^3.0.8
  settings_ui: ^2.0.2
  get: ^4.3.8
  enum_to_string: ^2.0.1
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  uuid: ^3.0.7
  provider: ^6.0.4
  rxdart: ^0.27.7
  flutter_vector_icons: ^2.0.0
  in_app_review: ^2.0.6
  url_launcher: ^6.1.7
  share: ^2.0.4

  google_mobile_ads: ^1.0.0
  app_tracking_transparency: ^2.0.3
  flutter_easyloading: ^3.0.5
  panara_dialogs: ^0.1.4
  new_version: ^0.3.1
  package_info_plus: ^1.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  blendthink_lints: ^3.0.0
  pedantic_mono: any
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.0
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "家計簿(節約)"

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: '#FFF422'
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/